# Generated by Django 4.2 on 2024-04-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedrule_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
