# Generated by Django 4.2 on 2024-04-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedrule_app', '0002_event_date_event_end_time_event_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
