# Generated by Django 4.2 on 2024-04-07 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedrule_app', '0005_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
