# Generated by Django 4.2 on 2024-04-07 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedrule_app', '0007_remove_event_date_remove_event_type_alter_event_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
